### ISSUE TITLE
Is adb_path missing in monkey-test-configs.yaml? 

### ISSUE THREAD

**Issue by lluviasnow** [Feri73/deep-gui#12]
https://github.com/Feri73/deep-gui/blob/66e6a7fac9cf40e0895980dc13f86ff958c00406/configs/monkey-test-configs.yaml#L136

Is it a bug about the missing adb_path in mokey-test-configs.yaml? 
After I fills the correct path, it works well, otherwise it will throw an exception because the testing code about Monkey++ uses the adb_path.
Thanks a lot.

**Comment by Feri73** [comment]
Yes that's a bug! Thanks for bringing it to my attention.
